### ISSUE TITLE
Optimizations

### ISSUE THREAD

**Issue by kirtanp98** [sriRacha21/rct-backend#1]
## List of Optimizations

- Save cache of already requested course for the the interval check, as soc data refreshes every 30
- Not sure about this but store a user's rToken for some amount of time as this won't change unless the users uninstall the app 

- A way to clean up old trackers, after add-drop week.

**Comment by kirtanp98** [comment]
rToken can refresh even when the user didn't reinstall the app. Example, my instance of the app.

**Comment by sriRacha21** [comment]
This needs to be reimplemented for Python
